all: multitap multitap_better

multitap: multitap.cpp main.cpp multitap.h
	g++ -Wall -g multitap.cpp main.cpp -o multitap

multitap_better: multitap_better.cpp main_better.cpp multitap_better.h
	g++ -Wall -g multitap_better.cpp main_better.cpp -o multitap_better


